### ISSUE TITLE
add new feature

### ISSUE THREAD

**Issue by JaberChowdhury** [JaberChowdhury/quotes-showcase#1]
``` tsx
const Scrollindicator = () => {
  return (
    <div className="w-full z-30 fixed top-0 left-0">
      <div
        id="indicator"
        className="h-full rounded-full p-1 bg-gradient-to-br from-rose-400 to-orange-300"
      ></div>
    </div>
  );
};

export default Scrollindicator;

```

``` css

#indicator {
  width: 100%;
  transform: scaleX(0);
  animation: indicator linear;
  transform-origin: left;
  animation-timeline: scroll();
}

@keyframes indicator {
  to {
    transform: scaleX(1);
  }
}

```
